version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Run the test and package the code...
      - sbt run       
  post_build:
    commands:
      - echo Build completed on `date`
      - sbt package
artifacts:
  files:
    - target/scala-2.11/core_2.11-1.0.0.jar